travis:
  secure:
    BINSTAR_TOKEN: Jyaj2pCUKyk4W7lTJYqXNz6KxXzj6Ad2FAbjzw9t1Fjtjj1mGwDKmDUlRInZ+ohyYmnEkb0MKZ8JfaY0D0ZX/3aUOFC+eQapQ6onfLCNejgxKYplVZO0Ptv6rc5DrS65zrxL5cn26/FkK1tEBYy0DOmZPDO/heSE3s54uYyu+DBEegEH22FHPjbN0RhucpKeORrjnwLbWPBlOWfUEnwD5NYQYyujmwNFYHHB9anwULN6mlx3VbAsej+lgICgUuLAQhZzVTsC1lTFCY5OHjdD54Y8UWkhBGBO6wA+BLtp02XypNeCXCNT5e1ebMwqfT8b/cgxWmxHdEU7wqnJPJAFfkRTIw8ZnPqpg+vvO/741v/2c/uTvk80unQO0vCevlJ3n8QUNOK2czG244TE4aKQYCWj/6HfW/Rfni4+Coa44lreIXdIdVKZBadPhnpY/OYMTPkxkp+mOT04jJaupyaKGLI1NtkXmwoq+oFwH7U1A+19Co/74l/HuH43BkxA/17Fsegnr8yfR27APMXWDVvwXUOUP7PrOwzTvK706cuyXSgrtLq9Ng0EVQMC5n+MO2In8wW/cDV8hC2Zv+M/MJqgDKvX0EhbFJFk9XCFJtNCSUdiO4PWY9lyaGYBVYzF7RD+RqfNz1ID5i12693MDJZIOPrHWv8Wp8zj66/g/KylGmM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
